name: Continuous Integration

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2.8.1
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build
          key: ${{ runner.os }}-gradle-
      - name: Run static code tests
        run: ./gradlew check
      - name: Check if code is packaged
        run: BUILD_VERSION=$(./gradlew -q pV)-$(date +%Y%m%d%H%M) ./gradlew -Pversion=$VERSION jar
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2.8.1
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build
          key: ${{ runner.os }}-gradle-
      - name: Publish signed jar file
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY}}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE}}
          OSS_USER: ${{ secrets.OSS_USER }}
          OSS_TOKEN: ${{ secrets.OSS_TOKEN }}
        run: |
          BUILD_VERSION=$(./gradlew -q pV)-$(date +%Y%m%d%H%M) ./gradlew -Pversion=$VERSION publish
